// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAieZueJsTIIWBUOtCY0pZojeGA0NUyT9U',
    appId: '1:242686240622:web:dc79c689012fac1606437f',
    messagingSenderId: '242686240622',
    projectId: 'expense-manager-b6d5c',
    authDomain: 'expense-manager-b6d5c.firebaseapp.com',
    storageBucket: 'expense-manager-b6d5c.firebasestorage.app',
    measurementId: 'G-BDKBTM2QPG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyALqUN7s84i5xzpug-tEdmgn9jeutLYrBc',
    appId: '1:242686240622:android:f1c95e4f65e3cd8f06437f',
    messagingSenderId: '242686240622',
    projectId: 'expense-manager-b6d5c',
    storageBucket: 'expense-manager-b6d5c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBeufRFUfAL3JpVvHqf7rtwa-nVY9T48ls',
    appId: '1:242686240622:ios:36b637f2cee3e71006437f',
    messagingSenderId: '242686240622',
    projectId: 'expense-manager-b6d5c',
    storageBucket: 'expense-manager-b6d5c.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBeufRFUfAL3JpVvHqf7rtwa-nVY9T48ls',
    appId: '1:242686240622:ios:36b637f2cee3e71006437f',
    messagingSenderId: '242686240622',
    projectId: 'expense-manager-b6d5c',
    storageBucket: 'expense-manager-b6d5c.firebasestorage.app',
    iosBundleId: 'com.example.expenseManager',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAieZueJsTIIWBUOtCY0pZojeGA0NUyT9U',
    appId: '1:242686240622:web:f010c425110cd25006437f',
    messagingSenderId: '242686240622',
    projectId: 'expense-manager-b6d5c',
    authDomain: 'expense-manager-b6d5c.firebaseapp.com',
    storageBucket: 'expense-manager-b6d5c.firebasestorage.app',
    measurementId: 'G-WCJ5SLK90B',
  );
}
